version: "3"
# For simplicity, we're keeping this file very small.
# From a security perspective, this docker compose shouldn't
# be considered "production ready".
services:
  node:
    build:
      context: .
      dockerfile: node-dockerfile
    image: "injection-fundamentals"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
      - NPM_CONFIG_LOGLEVEL info
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: ["npx", "${EXEC_MODE}", "${LESSON}"]
