server:
  port: 3000
application:
  domain: juice-sh.op
  name: 'Lip Gloss R Us haha'
  logo: JuiceShop_Logo.png
  favicon: favicon_v2.ico
  numberOfRandomFakeUsers: 1
  showChallengeSolvedNotifications: false
  showChallengeHints: false
  showVersionNumber: false
  theme: slate # Options: cerulean  cosmo  cyborg  darkly  flatly lumen  paper  readable  sandstone  simplex  slate  spacelab  superhero  united  yeti
  gitHubRibbon: none # Options: darkblue  gray  green  orange  red  white  none
  twitterUrl: 'https://twitter.com/owasp_juiceshop'
  facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
  planetOverlayMap: orangemap2k.jpg
  planetName: Orangeuze
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  altcoinName: Juicycoin
  cookieConsent:
    backgroundColor: '#eb6c44'
    textColor: '#ffffff'
    buttonColor: '#f5d948'
    buttonTextColor: '#000000'
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
products:
  -
    name: 'Wanda Gloss'
    price: 1.99
    description: 'Dont make your dreams come true... make your duckface come true :)'
    image: duck-face.jpg
    useForChristmasSpecialChallenge: true
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Muh Gloss'
    description: 'Makin your lips shine like the heavens'
    price: 99.99
    image: gloss1.jpg
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type``
  -
    name: 'Straight Up Glossin'
    description: 'You got to get your shine on'
    price: 0.01
    image: gloss.jpg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
ctf:
  countryMapping: ~
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
